### ISSUE TITLE
Error: an empty namespace may not be set when a resource name is provided.

### ISSUE THREAD

**Issue by Aracki** [Ladicle/kubectl-bindrole#24]
When I try to run:
```
kubectl rolesum -k Group system:authenticated
```
I am getting:
> Error: an empty namespace may not be set when a resource name is provided.

Also, I tried adding namespace with `-n <namespace>` but no difference.

rolesum version: **_1.4.0_**
kubectl version: **_1.17.1_**

**Comment by Ladicle** [comment]
I'm sorry to reply late. It has been fixed in v1.5.0.
