### ISSUE TITLE
explicit display of RoleBindings and ClusterRoleBindings

### ISSUE THREAD

**Issue by jpriebe** [Ladicle/kubectl-bindrole#26]
**Is your feature request related to a problem? Please describe.**
When I'm debugging RBAC issues, rolesum gives me almost everything I need, but it doesn't display which rolebindings or clusterrolebindings are binding the roles and clusterroles.

**Describe the solution you'd like**
Instead of

```
• Name: sample-namespace/sample-role
...
• Name: */sample-cluster-role
...
• Name: */sample-cluster-role2
```

It might be nice to see something like this:

```
• RB sample-namespace/sample-role-rolebinding ==> R sample-namespace/sample-role
...
• RB sample-namespace/sample-clusterrole-rolebinding ==> CR */sample-cluster-role
...
• CRB */sample-clusterrolebinding ==> CR */sample-cluster-role2
```

In other words, you could see if the policies are coming from a clusterrole or a role (and which one it is), and whether the binding is a rolebinding or a clusterrolebinding (and which one it is).

It seems like some of the information is indirectly available in the current rolesum output:

- if the Name starts with "*/", it's a ClusterRole; if it starts with a namespace name, then it's a Role
- if the resources have a ".*" on the end, it is a ClusterRoleBinding, otherwise it's a RoleBinding

But that's a little less explicit, and it doesn't tell you exactly which resource is doing the binding.

**Comment by jpriebe** [comment]
BTW -- I hate filing a feature request right after I find an amazing open source tool.  I don't want to give the impression that I don't appreciate the work you've done here.  This plugin will save me TONS of work in diagnosing RBAC problems.  Thanks for building this!

**Comment by jpriebe** [comment]
I submitted a PR for this feature.

**Comment by Ladicle** [comment]
ref: https://github.com/Ladicle/kubectl-rolesum/pull/27
