### ISSUE TITLE
Missing RoleBinding for Group and User

### ISSUE THREAD

**Issue by agaudreault** [Ladicle/kubectl-bindrole#31]
**Is your feature request related to a problem? Please describe.**
When we perform a `kubectl rolesum -k Group` or `kubectl rolesum -K User`, the RoleBindings in the current namespace are not returned.

**Describe the solution you'd like**
- When `-n <namespace>` is specified or the current context has a namespace, the command should return the ClusterRoleBindings and the RoleBindings.
- When a namespace is not set, only ClusterRoleBindings are returned.

**Describe alternatives you've considered**
- A flag could be added to ignore namespace `--ignore-namespace | --cluster-only` in case we cannot know if a namespace is set or not.

**Additional context**
We were trying to use the extension to summarize the permission of an user or AD group. Most of the permissions are given at the namespace level.

Problem started after fix for https://github.com/Ladicle/kubectl-rolesum/issues/29

**Comment by kouk** [comment]
I'm seeing the same issue, where I have a clusterrole, a service account in one namespace, and rolebindings in other namespaces binding the two. Pretty much the setup described [here](https://medium.com/faun/kubernetes-rbac-use-one-role-in-multiple-namespaces-d1d08bb08286). Rolesum doesn't see the rolebindings and policies remains empty.
