### ISSUE TITLE
installation via krew fails for the new arm64 release

### ISSUE THREAD

**Issue by the-gigi** [Ladicle/kubectl-bindrole#39]
**Describe the bug**

Installing via `krew` fails on Apple M1.

**To Reproduce**
1. Have a machine with Arm processor :-)
2. Run `kubectl krew install rolesum`
3. See error
```
$ kubectl krew install rolesum
Updated the local copy of plugin index.
Installing plugin: rolesum
W0528 09:40:35.196321   10093 install.go:164] failed to install plugin "rolesum": plugin "rolesum" does not offer installation for this platform
failed to install some plugins: [rolesum]: plugin "rolesum" does not offer installation for this platform
```

**Expected behavior**
rolesum should be installed correctly.

**Laptop (please complete the following information):**
 - Chip: Apple M1 Max
 - Processor: arm64
 - OS: macOS monterey 12.1

**Additional context**

Installation via `homebrew` works as expected.

**Comment by Ladicle** [comment]
It will be available after the following PR has been merged :)
https://github.com/kubernetes-sigs/krew-index/pull/2289
