### ISSUE TITLE
Failed to release v1.5.6

### ISSUE THREAD

**Issue by suzuki-shunsuke** [Ladicle/kubectl-bindrole#49]
It failed to release the latest version v1.5.6.

https://github.com/Ladicle/kubectl-rolesum/releases/tag/v1.5.6

<img width="265" alt="image" src="https://github.com/Ladicle/kubectl-rolesum/assets/13323303/f2647c2b-a4de-4d10-b65a-af4f4291f0d7">

https://github.com/Ladicle/kubectl-rolesum/actions/runs/8730791354/job/23955176692

```
Run echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
Error response from daemon: Get "https://registry-1.docker.io/v2/": unauthorized: your account must log in with a Personal Access Token (PAT) - learn more at docs.docker.com/go/access-tokens
Error: Process completed with exit code 1.
```

https://github.com/Ladicle/kubectl-rolesum/blob/579e54c33d83a98dfff57b2726a3ee8ca0ba357d/.github/workflows/release.yaml#L18-L24

> Error response from daemon: Get "https://registry-1.docker.io/v2/":
> unauthorized: your account must log in with a Personal Access Token (PAT)

https://docs.docker.com/security/for-developers/access-tokens/

**Comment by Ladicle** [comment]
Thank you for filing that detail! Fixed, and now artifacts are available.
