### ISSUE TITLE
Krew support

### ISSUE THREAD

**Issue by luisdavim** [Ladicle/kubectl-bindrole#6]
Hi, can you make your plugin available on Krew?

**Comment by corneliusweig** [comment]
I was just about to ask the same :)

Krew is a kubectl plugin manager (see https://github.com/kubernetes-sigs/krew).

What do you think of distributing this as a kubectl plugin named kubectl bindrole?

Why?

- kubectl plugins are becoming a thing now, we have over 30 plugins.
- kubectl bindrole is more natural and memorable than a custom binary name
- krew helps you package/distribute your tool on macOS, Linux and Windows so you don't deal with homebrew, apt/dnf, chocolatey etc separately.

I suspect there would be no code changes required. The release process would involve periodic updates to the plugin manifest file hosted at https://github.com/kubernetes-sigs/krew-index/tree/master/plugins.

**Comment by Ladicle** [comment]
Thank you for reporting! I noticed Krew after developing bindrole, and it does not follow the naming rule. bindrole is not available yet.
However, I realized it's helpful for everyone, so I'll support it.

**Comment by corneliusweig** [comment]
Great, if you need help and the documentation doesn't help, I'm happy to help.

**Comment by nlamirault** [comment]
I create a PR : https://github.com/kubernetes-sigs/krew-index/pull/180
@Ladicle could you provide a new version (1.1.0 ?) with sha256 checksums ?

**Comment by corneliusweig** [comment]
@nlamirault Thanks for taking this up. There's no need to make another release just for checksums. You can generate the checksums locally with `sha256sum`.

**Comment by Ladicle** [comment]
@nlamirault thank you for your help :) Now just released v1.1.0.
```
7e0da62a72041f482a99ed18dc908e57426e2cfc57a99200cf3e760be7501031  kubectl-bindrole_darwin-amd64.tar.gz
e9ca1368302c4e9348235022c288fec5974dcacf41f2745a0c235572ec84482b  kubectl-bindrole_linux-amd64.tar.gz
218cd8488a7d7516cc251c79983a7ae9d82f3903969efbdf283405297fdd8a27  kubectl-bindrole_windows-amd64.tar.gz
```

**Comment by nlamirault** [comment]
Thanks.
I've updated the PR :

```
$ krew install bindrole                          
Updated the local copy of plugin index.
Installing plugin: bindrole
Installed plugin: bindrole

$ kubectl bindrole --help                     
Usage of /home/nicolas/.krew/bin/kubectl-bindrole:
      --as string                      Username to impersonate for the operation
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --cache-dir string               Default HTTP cache directory (default "/home/nicolas/.kube/http-cache")
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to the kubeconfig file to use for CLI requests.
  -n, --namespace string               If present, the namespace scope for this CLI request
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
  -s, --server string                  The address and port of the Kubernetes API server
  -k, --subject-kind string            The Kind of subject which is bound Roles. (default "ServiceAccount")
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use
  -v, --version                        Print command version
pflag: help requested
```

**Comment by corneliusweig** [comment]
@Ladicle you did not submit the plugin to krew, even though you are the author of this plugin. Would you be ok to also maintain the plugin manifest in krew-index, so that krew users get the newest update? I think this would make most sense, as you will probably remain the main contributor here.
cc @nlamirault

**Comment by Ladicle** [comment]
@corneliusweig Yes, that's fine.

**Comment by ahmetb** [comment]
Pinging this again.

We actually now have release automation for plugins, so you actually don't even need to maintain your plugin on Krew manually. If there's anything else we can make you to bring your plugin on board, happy to help!

**Comment by Ladicle** [comment]
@ahmetb Thank you for reminding me. Release automation sounds great! After adding the long description commented in the previous Pull-Request, I would like to send the PR again.

Also, since kubectl-bindrole does not follow the naming convention, I would like to register this command as role-summary. In that case, do I need to rename the repository first?

**Comment by ahmetb** [comment]
Which part doesn’t follow the naming convention? Bindrole doesn’t sound bad to me. But it’s up to you.

**Comment by Ladicle** [comment]
I figured ”bind” is not appropriate because this command displays a summary of bound roles, rather than it binds roles. 
Actually, I felt it was not bad, so I'm going to register without renaming.

**Comment by ahmetb** [comment]
I recall on krew-index repo there was a repo-summary PR https://github.com/kubernetes-sigs/krew-index/pull/180 and that makes sense to have that name if that's what the plugin actually does. :) Repo rename might not be a bad idea if it is not binding roles.

**Comment by corneliusweig** [comment]
If you want to pick this up, you can work from the manifest by @nlamirault in kubernetes-sigs/krew-index#180. There were some open points to be fixed, so just have a look at this comment too: https://github.com/kubernetes-sigs/krew-index/pull/180#pullrequestreview-306870169
